services:
  my_custom_class:
    class: Silecust\BaseTheme\Service\TestService
    public: false
  Silecust\BaseTheme\Service\TestService: '@my_custom_class'

  Silecust\BaseTheme\EventSubscriber\EventSubscriber:
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@my_custom_class'
      - '@twig'